--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2024-06-30 10:46:36

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4908 (class 1262 OID 65019)
-- Name: db_futbol; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE db_futbol WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Ecuador.1252';


ALTER DATABASE db_futbol OWNER TO postgres;

\connect db_futbol

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 234 (class 1259 OID 65150)
-- Name: api_equipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_equipo (
    id_equipo integer NOT NULL,
    nombre_equipo character varying(50) NOT NULL,
    direccion character varying(200) NOT NULL,
    descripcion character varying(300) NOT NULL,
    numero_jugadores integer
);


ALTER TABLE public.api_equipo OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 65149)
-- Name: api_equipo_id_equipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_equipo ALTER COLUMN id_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_equipo_id_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 65170)
-- Name: api_equipo_partido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_equipo_partido (
    id_equipo_partido integer NOT NULL,
    resultado character varying(50) NOT NULL,
    goles_ganador integer NOT NULL,
    goles_perdedor integer NOT NULL,
    id_equipo_id integer NOT NULL,
    id_partido_id integer NOT NULL
);


ALTER TABLE public.api_equipo_partido OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 65169)
-- Name: api_equipo_partido_id_equipo_partido_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_equipo_partido ALTER COLUMN id_equipo_partido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_equipo_partido_id_equipo_partido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 65164)
-- Name: api_jugador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_jugador (
    id_jugador integer NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido character varying(50) NOT NULL,
    ano_nacimiento integer NOT NULL,
    posicion character varying(50) NOT NULL,
    nacionalidad character varying(50) NOT NULL,
    id_equipo_id integer
);


ALTER TABLE public.api_jugador OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 65163)
-- Name: api_jugador_id_jugador_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_jugador ALTER COLUMN id_jugador ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_jugador_id_jugador_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 65158)
-- Name: api_partido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_partido (
    id_partido integer NOT NULL,
    fecha_partido date NOT NULL,
    hora_partido time without time zone NOT NULL,
    numero_goles integer NOT NULL
);


ALTER TABLE public.api_partido OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 65157)
-- Name: api_partido_id_partido_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_partido ALTER COLUMN id_partido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_partido_id_partido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4896 (class 0 OID 65150)
-- Dependencies: 234
-- Data for Name: api_equipo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_equipo (id_equipo, nombre_equipo, direccion, descripcion, numero_jugadores) FROM stdin;
\.


--
-- TOC entry 4902 (class 0 OID 65170)
-- Dependencies: 240
-- Data for Name: api_equipo_partido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_equipo_partido (id_equipo_partido, resultado, goles_ganador, goles_perdedor, id_equipo_id, id_partido_id) FROM stdin;
\.


--
-- TOC entry 4900 (class 0 OID 65164)
-- Dependencies: 238
-- Data for Name: api_jugador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_jugador (id_jugador, nombre, apellido, ano_nacimiento, posicion, nacionalidad, id_equipo_id) FROM stdin;
\.


--
-- TOC entry 4898 (class 0 OID 65158)
-- Dependencies: 236
-- Data for Name: api_partido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_partido (id_partido, fecha_partido, hora_partido, numero_goles) FROM stdin;
\.


--
-- TOC entry 4909 (class 0 OID 0)
-- Dependencies: 233
-- Name: api_equipo_id_equipo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_equipo_id_equipo_seq', 1, false);


--
-- TOC entry 4910 (class 0 OID 0)
-- Dependencies: 239
-- Name: api_equipo_partido_id_equipo_partido_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_equipo_partido_id_equipo_partido_seq', 1, false);


--
-- TOC entry 4911 (class 0 OID 0)
-- Dependencies: 237
-- Name: api_jugador_id_jugador_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_jugador_id_jugador_seq', 1, false);


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 235
-- Name: api_partido_id_partido_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_partido_id_partido_seq', 1, false);


--
-- TOC entry 4748 (class 2606 OID 65174)
-- Name: api_equipo_partido api_equipo_partido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_equipo_partido
    ADD CONSTRAINT api_equipo_partido_pkey PRIMARY KEY (id_equipo_partido);


--
-- TOC entry 4739 (class 2606 OID 65156)
-- Name: api_equipo api_equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_equipo
    ADD CONSTRAINT api_equipo_pkey PRIMARY KEY (id_equipo);


--
-- TOC entry 4744 (class 2606 OID 65168)
-- Name: api_jugador api_jugador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_jugador
    ADD CONSTRAINT api_jugador_pkey PRIMARY KEY (id_jugador);


--
-- TOC entry 4741 (class 2606 OID 65162)
-- Name: api_partido api_partido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_partido
    ADD CONSTRAINT api_partido_pkey PRIMARY KEY (id_partido);


--
-- TOC entry 4745 (class 1259 OID 65191)
-- Name: api_equipo_partido_id_equipo_id_73625a63; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_equipo_partido_id_equipo_id_73625a63 ON public.api_equipo_partido USING btree (id_equipo_id);


--
-- TOC entry 4746 (class 1259 OID 65192)
-- Name: api_equipo_partido_id_partido_id_f0339510; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_equipo_partido_id_partido_id_f0339510 ON public.api_equipo_partido USING btree (id_partido_id);


--
-- TOC entry 4742 (class 1259 OID 65180)
-- Name: api_jugador_id_equipo_id_5bbfa186; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_jugador_id_equipo_id_5bbfa186 ON public.api_jugador USING btree (id_equipo_id);


--
-- TOC entry 4750 (class 2606 OID 65181)
-- Name: api_equipo_partido api_equipo_partido_id_equipo_id_73625a63_fk_api_equip; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_equipo_partido
    ADD CONSTRAINT api_equipo_partido_id_equipo_id_73625a63_fk_api_equip FOREIGN KEY (id_equipo_id) REFERENCES public.api_equipo(id_equipo) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4751 (class 2606 OID 65186)
-- Name: api_equipo_partido api_equipo_partido_id_partido_id_f0339510_fk_api_parti; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_equipo_partido
    ADD CONSTRAINT api_equipo_partido_id_partido_id_f0339510_fk_api_parti FOREIGN KEY (id_partido_id) REFERENCES public.api_partido(id_partido) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4749 (class 2606 OID 65193)
-- Name: api_jugador api_jugador_id_equipo_id_5bbfa186_fk_api_equipo_id_equipo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_jugador
    ADD CONSTRAINT api_jugador_id_equipo_id_5bbfa186_fk_api_equipo_id_equipo FOREIGN KEY (id_equipo_id) REFERENCES public.api_equipo(id_equipo) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2024-06-30 10:46:37

--
-- PostgreSQL database dump complete
--

